// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/repository.proto

package repository

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RepositoryService_PublishMeme_FullMethodName            = "/repository.RepositoryService/PublishMeme"
	RepositoryService_GetTopLongMemes_FullMethodName        = "/repository.RepositoryService/GetTopLongMemes"
	RepositoryService_SearchMemesBySubstring_FullMethodName = "/repository.RepositoryService/SearchMemesBySubstring"
	RepositoryService_GetMemesByMonth_FullMethodName        = "/repository.RepositoryService/GetMemesByMonth"
	RepositoryService_GetRandomMeme_FullMethodName          = "/repository.RepositoryService/GetRandomMeme"
)

// RepositoryServiceClient is the client API for RepositoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepositoryServiceClient interface {
	PublishMeme(ctx context.Context, in *PublishMemeRequest, opts ...grpc.CallOption) (*PublishMemeResponse, error)
	GetTopLongMemes(ctx context.Context, in *TopLongMemesRequest, opts ...grpc.CallOption) (*MemesResponse, error)
	SearchMemesBySubstring(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*MemesResponse, error)
	GetMemesByMonth(ctx context.Context, in *MonthRequest, opts ...grpc.CallOption) (*MemesResponse, error)
	GetRandomMeme(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MemeResponse, error)
}

type repositoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepositoryServiceClient(cc grpc.ClientConnInterface) RepositoryServiceClient {
	return &repositoryServiceClient{cc}
}

func (c *repositoryServiceClient) PublishMeme(ctx context.Context, in *PublishMemeRequest, opts ...grpc.CallOption) (*PublishMemeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishMemeResponse)
	err := c.cc.Invoke(ctx, RepositoryService_PublishMeme_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetTopLongMemes(ctx context.Context, in *TopLongMemesRequest, opts ...grpc.CallOption) (*MemesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemesResponse)
	err := c.cc.Invoke(ctx, RepositoryService_GetTopLongMemes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) SearchMemesBySubstring(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*MemesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemesResponse)
	err := c.cc.Invoke(ctx, RepositoryService_SearchMemesBySubstring_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetMemesByMonth(ctx context.Context, in *MonthRequest, opts ...grpc.CallOption) (*MemesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemesResponse)
	err := c.cc.Invoke(ctx, RepositoryService_GetMemesByMonth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetRandomMeme(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MemeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemeResponse)
	err := c.cc.Invoke(ctx, RepositoryService_GetRandomMeme_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServiceServer is the server API for RepositoryService service.
// All implementations must embed UnimplementedRepositoryServiceServer
// for forward compatibility.
type RepositoryServiceServer interface {
	PublishMeme(context.Context, *PublishMemeRequest) (*PublishMemeResponse, error)
	GetTopLongMemes(context.Context, *TopLongMemesRequest) (*MemesResponse, error)
	SearchMemesBySubstring(context.Context, *SearchRequest) (*MemesResponse, error)
	GetMemesByMonth(context.Context, *MonthRequest) (*MemesResponse, error)
	GetRandomMeme(context.Context, *Empty) (*MemeResponse, error)
	mustEmbedUnimplementedRepositoryServiceServer()
}

// UnimplementedRepositoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepositoryServiceServer struct{}

func (UnimplementedRepositoryServiceServer) PublishMeme(context.Context, *PublishMemeRequest) (*PublishMemeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMeme not implemented")
}
func (UnimplementedRepositoryServiceServer) GetTopLongMemes(context.Context, *TopLongMemesRequest) (*MemesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopLongMemes not implemented")
}
func (UnimplementedRepositoryServiceServer) SearchMemesBySubstring(context.Context, *SearchRequest) (*MemesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMemesBySubstring not implemented")
}
func (UnimplementedRepositoryServiceServer) GetMemesByMonth(context.Context, *MonthRequest) (*MemesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemesByMonth not implemented")
}
func (UnimplementedRepositoryServiceServer) GetRandomMeme(context.Context, *Empty) (*MemeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomMeme not implemented")
}
func (UnimplementedRepositoryServiceServer) mustEmbedUnimplementedRepositoryServiceServer() {}
func (UnimplementedRepositoryServiceServer) testEmbeddedByValue()                           {}

// UnsafeRepositoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepositoryServiceServer will
// result in compilation errors.
type UnsafeRepositoryServiceServer interface {
	mustEmbedUnimplementedRepositoryServiceServer()
}

func RegisterRepositoryServiceServer(s grpc.ServiceRegistrar, srv RepositoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedRepositoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepositoryService_ServiceDesc, srv)
}

func _RepositoryService_PublishMeme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMemeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).PublishMeme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_PublishMeme_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).PublishMeme(ctx, req.(*PublishMemeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetTopLongMemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopLongMemesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetTopLongMemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_GetTopLongMemes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetTopLongMemes(ctx, req.(*TopLongMemesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_SearchMemesBySubstring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).SearchMemesBySubstring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_SearchMemesBySubstring_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).SearchMemesBySubstring(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetMemesByMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetMemesByMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_GetMemesByMonth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetMemesByMonth(ctx, req.(*MonthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetRandomMeme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetRandomMeme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_GetRandomMeme_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetRandomMeme(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RepositoryService_ServiceDesc is the grpc.ServiceDesc for RepositoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepositoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.RepositoryService",
	HandlerType: (*RepositoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMeme",
			Handler:    _RepositoryService_PublishMeme_Handler,
		},
		{
			MethodName: "GetTopLongMemes",
			Handler:    _RepositoryService_GetTopLongMemes_Handler,
		},
		{
			MethodName: "SearchMemesBySubstring",
			Handler:    _RepositoryService_SearchMemesBySubstring_Handler,
		},
		{
			MethodName: "GetMemesByMonth",
			Handler:    _RepositoryService_GetMemesByMonth_Handler,
		},
		{
			MethodName: "GetRandomMeme",
			Handler:    _RepositoryService_GetRandomMeme_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/repository.proto",
}
