version: '3.8'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  parseservice:
    build:
      context: parseService
    depends_on:
      rabbit:
        condition: service_healthy

  repositoryservice:
      build:
        context: repositoryService
      ports:
        - "50051:50051"
        - "50052:50052"
      depends_on:
        rabbit:
          condition: service_healthy
        postgres:
          condition: service_healthy

  requesterservice:
    build:
      context: requesterService
    ports:
      - "50053:50053"
    depends_on:
      - repositoryservice

  telegram_bot:
    build:
      context: stepStepichBot
    depends_on:
      rabbit:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5