version: '3.8'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  parseservice:
    build:
      context: parseService
    depends_on:
      rabbit:
        condition: service_healthy

  repositoryservice:
      build:
        context: repositoryService
      ports:
        - "50051:50051"
      depends_on:
        - rabbit

  telegram_bot:
    build:
      context: stepStepichBot
    depends_on:
      rabbit:
        condition: service_healthy
    env_file:
      - .env