// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/api_publish.proto

package publish

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RepositoryServicePublish_PublishMeme_FullMethodName = "/api.RepositoryServicePublish/PublishMeme"
)

// RepositoryServicePublishClient is the client API for RepositoryServicePublish service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepositoryServicePublishClient interface {
	PublishMeme(ctx context.Context, in *PublishMemeRequest, opts ...grpc.CallOption) (*PublishMemeResponse, error)
}

type repositoryServicePublishClient struct {
	cc grpc.ClientConnInterface
}

func NewRepositoryServicePublishClient(cc grpc.ClientConnInterface) RepositoryServicePublishClient {
	return &repositoryServicePublishClient{cc}
}

func (c *repositoryServicePublishClient) PublishMeme(ctx context.Context, in *PublishMemeRequest, opts ...grpc.CallOption) (*PublishMemeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishMemeResponse)
	err := c.cc.Invoke(ctx, RepositoryServicePublish_PublishMeme_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServicePublishServer is the server API for RepositoryServicePublish service.
// All implementations must embed UnimplementedRepositoryServicePublishServer
// for forward compatibility.
type RepositoryServicePublishServer interface {
	PublishMeme(context.Context, *PublishMemeRequest) (*PublishMemeResponse, error)
	mustEmbedUnimplementedRepositoryServicePublishServer()
}

// UnimplementedRepositoryServicePublishServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepositoryServicePublishServer struct{}

func (UnimplementedRepositoryServicePublishServer) PublishMeme(context.Context, *PublishMemeRequest) (*PublishMemeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMeme not implemented")
}
func (UnimplementedRepositoryServicePublishServer) mustEmbedUnimplementedRepositoryServicePublishServer() {
}
func (UnimplementedRepositoryServicePublishServer) testEmbeddedByValue() {}

// UnsafeRepositoryServicePublishServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepositoryServicePublishServer will
// result in compilation errors.
type UnsafeRepositoryServicePublishServer interface {
	mustEmbedUnimplementedRepositoryServicePublishServer()
}

func RegisterRepositoryServicePublishServer(s grpc.ServiceRegistrar, srv RepositoryServicePublishServer) {
	// If the following call pancis, it indicates UnimplementedRepositoryServicePublishServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepositoryServicePublish_ServiceDesc, srv)
}

func _RepositoryServicePublish_PublishMeme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMemeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServicePublishServer).PublishMeme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryServicePublish_PublishMeme_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServicePublishServer).PublishMeme(ctx, req.(*PublishMemeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepositoryServicePublish_ServiceDesc is the grpc.ServiceDesc for RepositoryServicePublish service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepositoryServicePublish_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.RepositoryServicePublish",
	HandlerType: (*RepositoryServicePublishServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMeme",
			Handler:    _RepositoryServicePublish_PublishMeme_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/api_publish.proto",
}
